/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello_cs;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
		  HelloCS helloCS = new HelloCS();
		  helloCS.printMessage();
      helloCS.printClasses();
    }
}
